version: "3.9"
services:
        app:
                image: aoruetaa/proyecto
                container_name: proyecto
                links:
                        - neo4j
                depends_on:
                        - neo4j

        neo4j:
                image: neo4j:3.5
                container_name: neo4j
                environment:
                        - discovery.type=single-node
                        - NEO4J_AUTH=none
                volumes:
                        - ./conf:/conf
                        - ./data:/data
                        - ./import:/import
                        - ./logs:/logs
                        - ./plugins:/plugins
                ports:
                        - 7474:7474
                        - 7687:7687